#index:
#    path: /
#    controller: App\Controller\DefaultController::index
inicio:
  path: /inicio
  controller: APP\Controller\DefaultController::inicio
new:
  path: /new
  controller: APP\Controller\DefaultController::new
deleteTask:
  path: /deleteTask/{id}
  controller: APP\Controller\DefaultController::deleteTask
